name: CI & CD
on:
  workflow_dispatch:

env:
  WORKDIR: "/home/adminhha/MappingSite"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Stop Java service
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd
            sudo systemctl stop mapping-site.service
            
      - name: Stop Pgadmin & Postgres containers
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR
            sudo docker-compose down

      - name: Build Run on Server
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR
            ./gradlew build
            
      - name: Start Pgadmin & Postgres containers
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd $WORKDIR
            sudo docker-compose up -d
            
      - name: Start Java service
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            cd
            sudo systemctl start mapping-site.service
